config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :homes
  resources :galleries 
  resources :singlewide_pictures

 # root :to => 'galleries#index'
  root :to => 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
has_many :singlewide_pictures, :dependent => :destroy
end

app/models/singlewide_picture.rb
class SinglewidePicture < ApplicationRecord

belongs_to :gallery

  has_attached_file :image,
    :path => ":rails_root/public/images/:id/:filename",
    :url  => "/images/:id/:filename"

  do_not_validate_attachment_file_type :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
 before_action :set_profile

 def set_profile
 if params[:gallery_id].present?
 gallary = Gallery.where( id: params[:gallery_id])
# render text: gallery.to_yaml and return
 session[:selected_gallery] = @selected_gallery = params[:gallery_id] if gallery.present?
    else
      session[:selected_gallery] = @selected_gallery = nil;
    end
 end


  
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
# GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery  = Gallery.find(params[:id])
    @singlewide_pictures = @gallery.singlewide_pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save

        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.singlewide_pictures.create(image: image)
          }
        end

        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(gallery_params)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.singlewide_pictures.create(image: image)
          }
        end
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:description,
                                    :name,
                                    :no_of_bedrooms,
                                    :building_method, :series, :sft, :no_of_bathrooms, :other,
                                    :singlewide_pictures
                                   )
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def index

end

end

app/controllers/singlewide_pictures_controller.rb
class SinglewidePicturesController < ApplicationController

#before_action :set_gallery
# GET /pictures
  # GET /pictures.json
  def index

    @gallery = Gallery.find(params[:gallery_id])

    @singlewide_pictures = @gallery.singlewide_pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @singlewide_pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
#    @gallery = Gallery.find(params[:gallery_id])
#    gallery_id = session['selected_gallery'] if session['selected_gallery'].present?
 #   @gallery = Gallery.where(id:gallery_id)
  #  render text: gallery_id.to_yaml and return  
    @singlewide_picture = SinglewidePicture.find(params[:id])
#    render text: params[:gallery_id].to_yaml and return

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @singlewide_picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @gallery = Gallery.find(params[:gallery_id])
    @singlewide_picture = @gallery.singlewide_pictures.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
   # @gallery = Gallery.find(params[:gallery_id])

    @singlewide_picture = SinglewidePicture.find(params[:id])
    # @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @singlewide_picture = SinglewidePicture.new(params[:singlewide_picture])

    if @singlewide_picture.save
      respond_to do |format|
        format.html {
          render :json => [@singlewide_picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@singlewide_picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update

    @gallery = Gallery.find(params[:gallery_id])

    @singlewide_picture = @gallery.singlewide_pictures.find(params[:id])

    respond_to do |format|
      if @singlewide_picture.update_attributes(singlewide_picture_params)
        format.html { redirect_to gallery_path(@gallery), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @singlewide_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    #@gallery = Gallery.find(params[:gallery_id])
    #@picture = @gallery.pictures.find(params[:id])
    @singlewide_picture = SinglewidePicture.find(params[:id])
    @singlewide_picture.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def make_default
    @singlewide_picture = SinglewidePicture.find(params[:id])
    @gallery = Gallery.find(params[:gallery_id])

    @gallery.cover = @singlewide_picture.id
    @gallery.save

    respond_to do |format|
      format.js
    end
  end 

  def set_gallery 
    render text: params[:gallery_id].to_yaml and return

    if params[:gallery_id].present?
      gallary = Gallery.where( id: params[:gallery_id])
       #render text: gallery.to_yaml and return
      session[:selected_gallery] = @selected_gallery = params[:gallery_id] if gallery.present?
    else
         session[:selected_gallery] = @selected_gallery = nil;
    end
  end


  private

  def singlewide_picture_params
    params.require(:singlewide_picture).permit(:description, :gallery_id, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/singlewide_pictures_helper.rb
module SinglewidePicturesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :no_of_bedrooms, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :no_of_bedrooms, :class => 'text_field' %>
    </div>
  </div>

   <div class="control-group">
    <%= f.label :building_method, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :building_method, :class => 'text_field' %>
    </div>
  </div>

   <div class="control-group">
    <%= f.label :series, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :series, :class => 'text_field' %>
    </div>
  </div>

   <div class="control-group">
    <%= f.label :sft, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sft, :class => 'text_field' %>
    </div>
  </div>

 
   <div class="control-group">
    <%= f.label :no_of_bathrooms, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :no_of_bathrooms, :class => 'text_field' %>
    </div>
  </div>

    <div class="control-group">
    <%= f.label :other, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :other, :class => 'text_field' %>
    </div>
  </div>




  <div class="control-group">
    <%= f.label :pictures, :class => 'control-label' %>
    <div class="controls">
      <!-- The magic is coming ...look at my eyes....shazammmm -->
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galleries_path, :class => 'btn btn-mini' %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<%- model_class = @gallery.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/index.html.erb
<div class="row">
  <h1>Homes</h1>
  <%= link_to 'New', new_gallery_path, :class => 'btn btn-mini' %>
  <p></p>
  <ul class="thumbnails files">
    <% @galleries.each do |gallery| %>
        <li class="span4" id="gallery_<%= gallery.id %>">
          <div class="thumbnail">
            <% if gallery.singlewide_pictures.first %>
            <%= link_to image_tag(gallery.singlewide_pictures.first.image.url), gallery_path(gallery) %>
            <% else %>
              N/A
            <% end %>
            <div class="caption">
              <p style="text-align: center;">
                <%= gallery.name.truncate(14) %>
                <%= link_to "Show", gallery_path(gallery) %>
                <%= link_to "Edit", edit_gallery_path(gallery) %>
                <%= link_to "Delete", gallery,
                  :data => { :confirm => "Are you sure?" },
                  :method => :delete
                %>
              </p>
            </div>
          </div>
        </li>
    <% end %>
  </ul>

</div>

app/views/galleries/new.html.erb
<%- model_class = @gallery.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/show.html.erb
<div class="row">
  <h1>Gallery</h1>

  <input type="hidden" id="galleryID" value="<%= @gallery.id %>">

  <p>
    <b>Name: </b>
    <%= @gallery.name %>
  </p>

  <p>
    <b>Description: </b>
    <%= @gallery.description %>
  </p>
 
  <p>
    <b>Number of Bathrooms: </b>
    <%= @gallery.no_of_bathrooms %>
  </p>
  
   <p>
    <b>Building method: </b>
    <%= @gallery.building_method %>
  </p>

   <p>
    <b>Series: </b>
    <%= @gallery.series %>
  </p>


   <p>
    <b>Sq.feet: </b>
    <%= @gallery.sft %>
  </p>


   <p>
    <b>Number of Bedrooms: </b>
    <%= @gallery.no_of_bedrooms %>
  </p>

  <p>
    <b>Name: </b>
    <%= @gallery.name %>
  </p>


  <p>
    <b>Other Details: </b>
    <%= @gallery.other %>
  </p>




  <div class="form-actions">
    <%= link_to 'Back', galleries_path, :class => 'btn btn-mini'  %>
    <%= link_to 'Edit gallery', edit_gallery_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Delete gallery', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
  </div>

<h2>Pictures</h2>
</div>
 

<div class="row">
  <ul class="thumbnails files">
<% unless @singlewide_pictures.empty? %>
  <% @singlewide_pictures.each do |pic| %>
    <li class="span3" id="singlewide_picture_<%= pic.id %>">
    <div class="thumbnail">
      <%= image_tag pic.image.url %>
      <div class="caption">
        <p style="text-align: center;">
        <%= link_to "Edit picture", singlewide_picture_path(pic) %>

        <%=
          link_to "Delete picture", pic,
            :data => { :confirm => "Are you sure?" },
            :method => :delete
          %>

        </p>
      </div>
    </div>
    </li>
  <% end %>
<% end %>
</ul>
</div>

app/views/homes/index.html.erb
<div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <h2>Homes</h2>

          <p>Innovation...... Enriched</p>
        </div>
      </div>
      <!-- /.row -->
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homes</title>
    <%= csrf_meta_tags %>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= url_for galleries_path %>">Singlewide-Homes</a></li>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <%= yield %>
  </body>
</html>

app/views/singlewide_pictures/_form.html.erb
<%= form_for(@singlwide_picture) do |f| %>
  

  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    
       

app/views/singlewide_pictures/edit.html.erb
<div class="page-header">
  <h1>Edit Picture</h1>
</div>
<%= render :partial => 'form' %>

app/views/singlewide_pictures/index.html.erb
<%- model_class = SinglewidePicture.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:gallery_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @singlewide_pictures.each do |singlewide_picture| %>
      <tr>
        <td><%= link_to singlewide_picture.id, singlewide_picture_path(singlewide_picture) %></td>
        <td><%= singlewide_picture.description %></td>
        <td><%= singlewide_picture.image %></td>
        <td><%= singlewide_picture.gallery_id %></td>
        <td><%= singlewide_picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_singlewide_picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      singlewide_picture_path(singlewide_picture),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_singlewide_picture_path,
            :class => 'btn btn-primary' %>

app/views/singlewide_pictures/new.html.erb
<%- model_class = @singlewide_picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/singlewide_pictures/show.html.erb
<%- model_class = @gallery.class -%>

<%- model_class = @singlewide_picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @singlewide_picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @singlewide_picture.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gallery_id) %>:</strong></dt>
  <dd><%= @singlewide_picture.gallery_id %></dd>
</dl>



<%= image_tag @singlewide_picture.image.url %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gallery_path(@singlewide_picture.gallery_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_singlewide_picture_path(@singlewide_picture), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              singlewide_picture_path(@singlewide_picture),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>